apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1deployment
  labels:
    app: micro1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro1
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
      - name: micro1
        image: microservice1:1.0
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: micro1service
spec:
  selector:
    app.kubernetes.io/name: micro1
  ports:
  type: NodePort
    - protocol: TCP
      port: 3001
      targetPort: 3001